// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/attrdedup/dedup_test.go.tmpl

package attrnorm

import (
	"testing"

	"github.com/google/go-cmp/cmp"

	"go.opentelemetry.io/otel/attribute"
)

var cmpValue = cmp.AllowUnexported(attribute.Value{})

func TestValueDedup(t *testing.T) {
	tests := []struct {
		name        string
		value       attribute.Value
		want        attribute.Value
		wantChanged bool
	}{
		{
			name: "unique map",
			value: attribute.MapValue(
				attribute.String("one", "1"),
				attribute.String("two", "2"),
			),
			want: attribute.MapValue(
				attribute.String("one", "1"),
				attribute.String("two", "2"),
			),
			wantChanged: false,
		},
		{
			name: "duplicate map",
			value: attribute.MapValue(
				attribute.String("one", "1"),
				attribute.String("one", "2"),
				attribute.String("two", "3"),
			),
			want: attribute.MapValue(
				attribute.String("one", "2"),
				attribute.String("two", "3"),
			),
			wantChanged: true,
		},
		{
			name: "duplicate map after prior key",
			value: attribute.MapValue(
				attribute.String("a", "1"),
				attribute.String("b", "2"),
				attribute.String("b", "3"),
				attribute.String("c", "4"),
			),
			want: attribute.MapValue(
				attribute.String("a", "1"),
				attribute.String("b", "3"),
				attribute.String("c", "4"),
			),
			wantChanged: true,
		},
		{
			name: "nested map",
			value: attribute.MapValue(
				attribute.Map(
					"outer",
					attribute.String("inner", "1"),
					attribute.String("inner", "2"),
				),
			),
			want: attribute.MapValue(
				attribute.Map(
					"outer",
					attribute.String("inner", "2"),
				),
			),
			wantChanged: true,
		},
		{
			name: "map inside slice",
			value: attribute.SliceValue(
				attribute.StringValue("prior"),
				attribute.MapValue(
					attribute.String("inner", "1"),
					attribute.String("inner", "2"),
				),
				attribute.StringValue("tail"),
			),
			want: attribute.SliceValue(
				attribute.StringValue("prior"),
				attribute.MapValue(
					attribute.String("inner", "2"),
				),
				attribute.StringValue("tail"),
			),
			wantChanged: true,
		},
		{
			name: "unique slice",
			value: attribute.SliceValue(
				attribute.StringValue("one"),
				attribute.IntValue(2),
			),
			want: attribute.SliceValue(
				attribute.StringValue("one"),
				attribute.IntValue(2),
			),
			wantChanged: false,
		},
		{
			name: "empty and invalid keys",
			value: attribute.MapValue(
				attribute.KeyValue{},
				attribute.String("", "empty"),
				attribute.String("valid", "value"),
			),
			want: attribute.MapValue(
				attribute.String("", "empty"),
				attribute.String("valid", "value"),
			),
			wantChanged: true,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			got, changed := ValueDedup(test.value)
			if changed != test.wantChanged {
				t.Fatalf("ValueDedup() changed = %v, want %v", changed, test.wantChanged)
			}
			if diff := cmp.Diff(test.want, got, cmpValue); diff != "" {
				t.Fatalf("ValueDedup() mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

func TestValueWithDepthLimit(t *testing.T) {
	tests := []struct {
		name        string
		limit       int
		value       attribute.Value
		want        attribute.Value
		wantChanged bool
	}{
		{
			name:  "below limit",
			limit: 3,
			value: attribute.MapValue(
				attribute.Map(
					"level1",
					attribute.Map(
						"level2",
						attribute.String("leaf", "value"),
					),
				),
			),
			want: attribute.MapValue(
				attribute.Map(
					"level1",
					attribute.Map(
						"level2",
						attribute.String("leaf", "value"),
					),
				),
			),
		},
		{
			name:  "at limit",
			limit: 2,
			value: attribute.MapValue(
				attribute.Map(
					"level1",
					attribute.String("leaf", "value"),
				),
			),
			want: attribute.MapValue(
				attribute.Map(
					"level1",
					attribute.String("leaf", "value"),
				),
			),
		},
		{
			name:  "map over limit",
			limit: 2,
			value: attribute.MapValue(
				attribute.Map(
					"level1",
					attribute.Map(
						"level2",
						attribute.Map("over", attribute.String("leaf", "value")),
					),
				),
			),
			want: attribute.MapValue(
				attribute.Map(
					"level1",
					attribute.KeyValue{Key: "level2"},
				),
			),
			wantChanged: true,
		},
		{
			name:  "slice over limit",
			limit: 1,
			value: attribute.SliceValue(
				attribute.SliceValue(attribute.StringValue("over")),
				attribute.StringValue("leaf"),
			),
			want: attribute.SliceValue(
				attribute.Value{},
				attribute.StringValue("leaf"),
			),
			wantChanged: true,
		},
		{
			name:        "zero allows scalar",
			limit:       0,
			value:       attribute.StringValue("leaf"),
			want:        attribute.StringValue("leaf"),
			wantChanged: false,
		},
		{
			name:        "zero replaces collection",
			limit:       0,
			value:       attribute.SliceValue(attribute.StringValue("leaf")),
			want:        attribute.Value{},
			wantChanged: true,
		},
		{
			name:  "negative disables depth limit",
			limit: -1,
			value: attribute.MapValue(
				attribute.Map(
					"level1",
					attribute.Map(
						"level2",
						attribute.Map(
							"level3",
							attribute.String("leaf", "value"),
						),
					),
				),
			),
			want: attribute.MapValue(
				attribute.Map(
					"level1",
					attribute.Map(
						"level2",
						attribute.Map(
							"level3",
							attribute.String("leaf", "value"),
						),
					),
				),
			),
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			got, changed := ValueWithDepthLimit(test.value, test.limit)
			if changed != test.wantChanged {
				t.Fatalf("ValueWithDepthLimit() changed = %v, want %v", changed, test.wantChanged)
			}
			if diff := cmp.Diff(test.want, got, cmpValue); diff != "" {
				t.Fatalf("ValueWithDepthLimit() mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

func TestValueLimitDepthPreservesDuplicateMapKeys(t *testing.T) {
	value := attribute.MapValue(
		attribute.String("dup", "first"),
		attribute.String("dup", "second"),
		attribute.Map("over", attribute.String("leaf", "value")),
	)
	want := attribute.MapValue(
		attribute.String("dup", "first"),
		attribute.String("dup", "second"),
		attribute.KeyValue{Key: "over"},
	)

	got, changed := ValueLimitDepth(value, 1)
	if !changed {
		t.Fatal("ValueLimitDepth() changed = false, want true")
	}
	if diff := cmp.Diff(want, got, cmpValue); diff != "" {
		t.Fatalf("ValueLimitDepth() mismatch (-want +got):\n%s", diff)
	}
}

func TestValueDedupNoopAllocationFree(t *testing.T) {
	value := attribute.MapValue(
		attribute.String("one", "1"),
		attribute.String("two", "2"),
	)
	var got attribute.Value

	allocs := testing.AllocsPerRun(1000, func() {
		got, _ = ValueDedup(value)
	})
	if allocs != 0 {
		t.Fatalf("ValueDedup() allocations = %v, want 0", allocs)
	}
	if _, changed := ValueDedup(value); changed {
		t.Fatal("ValueDedup() changed a no-op input")
	}
	if diff := cmp.Diff(value, got, cmpValue); diff != "" {
		t.Fatalf("ValueDedup() mismatch (-want +got):\n%s", diff)
	}
}

func TestValueDedupStorageShapes(t *testing.T) {
	for n := 0; n <= 6; n++ {
		t.Run("map", func(t *testing.T) {
			kvs := make([]attribute.KeyValue, n)
			for i := range kvs {
				kvs[i] = attribute.Int(string(rune('a'+i)), i)
			}
			value := attribute.MapValue(kvs...)

			got, changed := ValueDedup(value)
			if changed {
				t.Fatal("ValueDedup() changed a no-op input")
			}
			if diff := cmp.Diff(value, got, cmpValue); diff != "" {
				t.Fatalf("ValueDedup() mismatch (-want +got):\n%s", diff)
			}
		})
		t.Run("slice", func(t *testing.T) {
			values := make([]attribute.Value, n)
			for i := range values {
				values[i] = attribute.IntValue(i)
			}
			value := attribute.SliceValue(values...)

			got, changed := ValueDedup(value)
			if changed {
				t.Fatal("ValueDedup() changed a no-op input")
			}
			if diff := cmp.Diff(value, got, cmpValue); diff != "" {
				t.Fatalf("ValueDedup() mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

func TestKeyValueDedup(t *testing.T) {
	kv := attribute.Map(
		"map",
		attribute.String("nested", "first"),
		attribute.String("nested", "second"),
	)
	want := attribute.Map(
		"map",
		attribute.String("nested", "second"),
	)

	got, changed := KeyValueDedup(kv)
	if !changed {
		t.Fatal("KeyValueDedup() changed = false, want true")
	}
	if diff := cmp.Diff(want, got, cmpValue); diff != "" {
		t.Fatalf("KeyValueDedup() mismatch (-want +got):\n%s", diff)
	}
}

func TestKeyValueWithDepthLimit(t *testing.T) {
	kv := attribute.Map(
		"map",
		attribute.Map(
			"level1",
			attribute.Map("over", attribute.String("leaf", "value")),
		),
	)
	want := attribute.Map(
		"map",
		attribute.Map(
			"level1",
			attribute.KeyValue{Key: "over"},
		),
	)

	got, changed := KeyValueWithDepthLimit(kv, 2)
	if !changed {
		t.Fatal("KeyValueWithDepthLimit() changed = false, want true")
	}
	if diff := cmp.Diff(want, got, cmpValue); diff != "" {
		t.Fatalf("KeyValueWithDepthLimit() mismatch (-want +got):\n%s", diff)
	}
}

func TestKeyValuesNoopReturnsInput(t *testing.T) {
	kvs := []attribute.KeyValue{
		attribute.String("one", "1"),
		attribute.Map("two", attribute.String("nested", "value")),
	}

	got, changed := KeyValuesDedup(kvs)
	if changed {
		t.Fatal("KeyValuesDedup() changed a no-op input")
	}
	if len(got) != len(kvs) {
		t.Fatalf("KeyValuesDedup() length = %d, want %d", len(got), len(kvs))
	}
	if &got[0] != &kvs[0] {
		t.Fatal("KeyValuesDedup() copied a no-op input")
	}
}

func TestKeyValuesDedup(t *testing.T) {
	kvs := []attribute.KeyValue{
		attribute.String("top", "value"),
		attribute.Map(
			"map",
			attribute.String("nested", "first"),
			attribute.String("nested", "second"),
		),
		attribute.String("tail", "value"),
	}
	want := []attribute.KeyValue{
		attribute.String("top", "value"),
		attribute.Map(
			"map",
			attribute.String("nested", "second"),
		),
		attribute.String("tail", "value"),
	}

	got, changed := KeyValuesDedup(kvs)
	if !changed {
		t.Fatal("KeyValuesDedup() changed = false, want true")
	}
	if diff := cmp.Diff(want, got, cmpValue); diff != "" {
		t.Fatalf("KeyValuesDedup() mismatch (-want +got):\n%s", diff)
	}
}

func TestKeyValuesWithDepthLimit(t *testing.T) {
	kvs := []attribute.KeyValue{
		attribute.String("top", "value"),
		attribute.Map(
			"map",
			attribute.Map(
				"level1",
				attribute.Map("over", attribute.String("leaf", "value")),
			),
		),
		attribute.String("tail", "value"),
	}
	want := []attribute.KeyValue{
		attribute.String("top", "value"),
		attribute.Map(
			"map",
			attribute.Map(
				"level1",
				attribute.KeyValue{Key: "over"},
			),
		),
		attribute.String("tail", "value"),
	}

	got, changed := KeyValuesWithDepthLimit(kvs, 2)
	if !changed {
		t.Fatal("KeyValuesWithDepthLimit() changed = false, want true")
	}
	if diff := cmp.Diff(want, got, cmpValue); diff != "" {
		t.Fatalf("KeyValuesWithDepthLimit() mismatch (-want +got):\n%s", diff)
	}
}

func TestSetDedup(t *testing.T) {
	set := attribute.NewSet(
		attribute.String("a-top", "value"),
		attribute.Map(
			"m-map",
			attribute.String("nested", "first"),
			attribute.String("nested", "second"),
		),
		attribute.String("z-tail", "value"),
	)
	want := attribute.NewSet(
		attribute.String("a-top", "value"),
		attribute.Map(
			"m-map",
			attribute.String("nested", "second"),
		),
		attribute.String("z-tail", "value"),
	)

	got, changed := SetDedup(set)
	if !changed {
		t.Fatal("SetDedup() changed = false, want true")
	}
	if diff := cmp.Diff(want.ToSlice(), got.ToSlice(), cmpValue); diff != "" {
		t.Fatalf("SetDedup() mismatch (-want +got):\n%s", diff)
	}
}

func TestSetWithDepthLimit(t *testing.T) {
	set := attribute.NewSet(
		attribute.String("a-top", "value"),
		attribute.Map(
			"m-map",
			attribute.Map(
				"level1",
				attribute.Map("over", attribute.String("leaf", "value")),
			),
		),
		attribute.String("z-tail", "value"),
	)
	want := attribute.NewSet(
		attribute.String("a-top", "value"),
		attribute.Map(
			"m-map",
			attribute.Map(
				"level1",
				attribute.KeyValue{Key: "over"},
			),
		),
		attribute.String("z-tail", "value"),
	)

	got, changed := SetWithDepthLimit(set, 2)
	if !changed {
		t.Fatal("SetWithDepthLimit() changed = false, want true")
	}
	if diff := cmp.Diff(want.ToSlice(), got.ToSlice(), cmpValue); diff != "" {
		t.Fatalf("SetWithDepthLimit() mismatch (-want +got):\n%s", diff)
	}
}

func TestSetDedupNoop(t *testing.T) {
	set := attribute.NewSet(
		attribute.String("top", "value"),
		attribute.Map("map", attribute.String("nested", "value")),
	)

	got, changed := SetDedup(set)
	if changed {
		t.Fatal("SetDedup() changed a no-op input")
	}
	if !got.Equals(&set) {
		t.Fatal("SetDedup() changed a no-op input")
	}
}

func TestSetDedupEmpty(t *testing.T) {
	set := attribute.Set{}

	got, changed := SetDedup(set)
	if changed {
		t.Fatal("SetDedup() changed an empty input")
	}
	if !got.Equals(&set) {
		t.Fatal("SetDedup() changed an empty input")
	}
}

func TestInvalidArrayStorage(t *testing.T) {
	if got := arrayLen("invalid", valueType); got != 0 {
		t.Fatalf("arrayLen() = %d, want 0", got)
	}

	if got := arrayAt[attribute.Value]("invalid", valueType, 0); got.Type() != attribute.EMPTY {
		t.Fatalf("arrayAt() = %v, want empty value", got)
	}
	if got := arrayAt[attribute.Value](
		[1]attribute.Value{attribute.StringValue("value")},
		keyValueType,
		0,
	); got.Type() != attribute.EMPTY {
		t.Fatalf("arrayAt() = %v, want empty value", got)
	}
	if got := arrayAt[attribute.Value](
		[1]attribute.Value{attribute.StringValue("value")},
		valueType,
		-1,
	); got.Type() != attribute.EMPTY {
		t.Fatalf("arrayAt() = %v, want empty value", got)
	}
}
