// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package exporter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[START_SPAN-1]
	_ = x[END_SPAN-2]
	_ = x[ADD_EVENT-3]
	_ = x[NEW_SCOPE-4]
	_ = x[MODIFY_ATTR-5]
	_ = x[SET_STATUS-6]
	_ = x[SET_NAME-7]
	_ = x[SINGLE_METRIC-8]
	_ = x[BATCH_METRIC-9]
}

const _EventType_name = "INVALIDSTART_SPANEND_SPANADD_EVENTNEW_SCOPEMODIFY_ATTRSET_STATUSSET_NAMESINGLE_METRICBATCH_METRIC"

var _EventType_index = [...]uint8{0, 7, 17, 25, 34, 43, 54, 64, 72, 85, 97}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
