// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package exporter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[START_SPAN-1]
	_ = x[FINISH_SPAN-2]
	_ = x[ADD_EVENT-3]
	_ = x[NEW_SCOPE-4]
	_ = x[NEW_MEASURE-5]
	_ = x[NEW_METRIC-6]
	_ = x[MODIFY_ATTR-7]
	_ = x[RECORD_STATS-8]
	_ = x[SET_STATUS-9]
	_ = x[SET_NAME-10]
}

const _EventType_name = "INVALIDSTART_SPANFINISH_SPANADD_EVENTNEW_SCOPENEW_MEASURENEW_METRICMODIFY_ATTRRECORD_STATSSET_STATUSSET_NAME"

var _EventType_index = [...]uint8{0, 7, 17, 28, 37, 46, 57, 67, 78, 90, 100, 108}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
