codecov:
  require_ci_to_pass: yes

ignore:
  - "exporters/otlp/internal/opentelemetry-proto-gen/**/*"
  - "exporters/trace/jaeger/internal/gen-go/**/*"

coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: yes
