version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
