// Code generated by "stringer -type=InstrumentKind"; DO NOT EDIT.

package otel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueRecorderKind-0]
	_ = x[ValueObserverKind-1]
	_ = x[CounterKind-2]
	_ = x[UpDownCounterKind-3]
	_ = x[SumObserverKind-4]
	_ = x[UpDownSumObserverKind-5]
}

const _InstrumentKind_name = "ValueRecorderKindValueObserverKindCounterKindUpDownCounterKindSumObserverKindUpDownSumObserverKind"

var _InstrumentKind_index = [...]uint8{0, 17, 34, 45, 62, 77, 98}

func (i InstrumentKind) String() string {
	if i < 0 || i >= InstrumentKind(len(_InstrumentKind_index)-1) {
		return "InstrumentKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstrumentKind_name[_InstrumentKind_index[i]:_InstrumentKind_index[i+1]]
}
