// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/otlpjson/common_test.go.tmpl

package otlpjson

import (
	"encoding/json"
	"math"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	commonpb "go.opentelemetry.io/proto/otlp/common/v1"
)

func TestMarshalNonFiniteDoubleValuesAsStrings(t *testing.T) {
	tests := []struct {
		name  string
		value float64
		want  string
	}{
		{name: "NaN", value: math.NaN(), want: "NaN"},
		{name: "positive infinity", value: math.Inf(1), want: "Infinity"},
		{name: "negative infinity", value: math.Inf(-1), want: "-Infinity"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			av := encodeAnyValue(&commonpb.AnyValue{Value: &commonpb.AnyValue_DoubleValue{
				DoubleValue: test.value,
			}})
			data, err := json.Marshal(av)
			require.NoError(t, err)
			assert.JSONEq(t, `{"doubleValue":"`+test.want+`"}`, string(data))
		})
	}
}

func TestMarshalEmptyBytesValuePreservesPresence(t *testing.T) {
	av := encodeAnyValue(&commonpb.AnyValue{Value: &commonpb.AnyValue_BytesValue{
		BytesValue: []byte{},
	}})
	data, err := json.Marshal(av)
	require.NoError(t, err)
	assert.JSONEq(t, `{"bytesValue":""}`, string(data))

	got := decodeAnyValue(av)
	require.NotNil(t, got)
	_, ok := got.Value.(*commonpb.AnyValue_BytesValue)
	require.True(t, ok, "expected BytesValue variant")
	assert.Empty(t, got.GetBytesValue())
}

func TestUnmarshalAcceptsIntAndUint64AsStringOrNumber(t *testing.T) {
	for _, tc := range []struct {
		name  string
		value string
	}{
		{"uint64_as_string", `"1617187200000000000"`},
		{"uint64_as_number", `1617187200000000000`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var i Uint64
			require.NoError(t, json.Unmarshal([]byte(tc.value), &i))
			assert.Equal(t, uint64(1617187200000000000), uint64(i))
		})
	}

	for _, tc := range []struct {
		name  string
		value string
	}{
		{"int64_as_string", `"-42"`},
		{"int64_as_number", `-42`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var i Int64
			require.NoError(t, json.Unmarshal([]byte(tc.value), &i))
			assert.Equal(t, int64(-42), int64(i))
		})
	}
}

func TestUnmarshalAcceptsFiniteDoubleAsStringOrNumber(t *testing.T) {
	for _, tc := range []struct {
		name  string
		value string
		want  float64
	}{
		{"as_string", `"1.2"`, 1.2},
		{"as_string_E_notation", `"5.678e4"`, 56780},
		{"as_number", `1.2`, 1.2},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var f Float64
			require.NoError(t, json.Unmarshal([]byte(tc.value), &f))
			assert.InDelta(t, tc.want, float64(f), 0)
		})
	}
}

func TestUnmarshalRejectsInvalidDoubleStrings(t *testing.T) {
	for _, tc := range []struct {
		name  string
		value string
	}{
		{"not_a_number", `"not a number"`},
		{"leading_space", `" 1.2"`},
		{"hexadecimal", `"0x1p2"`},
		{"noncanonical_infinity", `"Inf"`},
		{"nested_string", `"\"1.2\""`},
		{"out_of_range", `"1.79e309"`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var f Float64
			require.Error(t, json.Unmarshal([]byte(tc.value), &f))
		})
	}
}

func TestAnyValueRoundTrip(t *testing.T) {
	tests := []struct {
		name  string
		proto *commonpb.AnyValue
		check func(t *testing.T, got *commonpb.AnyValue)
	}{
		{
			name:  "string",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_StringValue{StringValue: "hello"}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				assert.Equal(t, "hello", got.GetStringValue())
			},
		},
		{
			name:  "bool_true",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_BoolValue{BoolValue: true}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				assert.True(t, got.GetBoolValue())
			},
		},
		{
			name:  "bool_false",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_BoolValue{BoolValue: false}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				_, ok := got.Value.(*commonpb.AnyValue_BoolValue)
				require.True(t, ok, "expected BoolValue variant")
				assert.False(t, got.GetBoolValue())
			},
		},
		{
			name:  "int",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_IntValue{IntValue: 42}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				assert.Equal(t, int64(42), got.GetIntValue())
			},
		},
		{
			name:  "double",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_DoubleValue{DoubleValue: 3.14}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				assert.InEpsilon(t, 3.14, got.GetDoubleValue(), 1e-9)
			},
		},
		{
			name:  "NaN",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_DoubleValue{DoubleValue: math.NaN()}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				assert.True(t, math.IsNaN(got.GetDoubleValue()))
			},
		},
		{
			name:  "positive_infinity",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_DoubleValue{DoubleValue: math.Inf(1)}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				assert.True(t, math.IsInf(got.GetDoubleValue(), 1))
			},
		},
		{
			name:  "negative_infinity",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_DoubleValue{DoubleValue: math.Inf(-1)}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				assert.True(t, math.IsInf(got.GetDoubleValue(), -1))
			},
		},
		{
			name: "bytes",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_BytesValue{
				BytesValue: []byte{0xDE, 0xAD, 0xBE, 0xEF},
			}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				assert.Equal(t, []byte{0xDE, 0xAD, 0xBE, 0xEF}, got.GetBytesValue())
			},
		},
		{
			name: "empty_bytes",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_BytesValue{
				BytesValue: []byte{},
			}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				_, ok := got.Value.(*commonpb.AnyValue_BytesValue)
				require.True(t, ok, "expected BytesValue variant")
				assert.Empty(t, got.GetBytesValue())
			},
		},
		{
			name: "array_of_mixed_values",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_ArrayValue{
				ArrayValue: &commonpb.ArrayValue{Values: []*commonpb.AnyValue{
					{Value: &commonpb.AnyValue_StringValue{StringValue: "a"}},
					{Value: &commonpb.AnyValue_IntValue{IntValue: 1}},
					{Value: &commonpb.AnyValue_BoolValue{BoolValue: true}},
				}},
			}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				arr := got.GetArrayValue()
				require.NotNil(t, arr)
				require.Len(t, arr.Values, 3)
				assert.Equal(t, "a", arr.Values[0].GetStringValue())
				assert.Equal(t, int64(1), arr.Values[1].GetIntValue())
				assert.True(t, arr.Values[2].GetBoolValue())
			},
		},
		{
			name: "kvlist",
			proto: &commonpb.AnyValue{Value: &commonpb.AnyValue_KvlistValue{
				KvlistValue: &commonpb.KeyValueList{Values: []*commonpb.KeyValue{
					{
						Key:   "k",
						Value: &commonpb.AnyValue{Value: &commonpb.AnyValue_StringValue{StringValue: "v"}},
					},
				}},
			}},
			check: func(t *testing.T, got *commonpb.AnyValue) {
				kv := got.GetKvlistValue()
				require.NotNil(t, kv)
				require.Len(t, kv.Values, 1)
				assert.Equal(t, "k", kv.Values[0].Key)
				assert.Equal(t, "v", kv.Values[0].Value.GetStringValue())
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			encoded := encodeAnyValue(test.proto)
			data, err := json.Marshal(encoded)
			require.NoError(t, err)

			var decoded AnyValue
			require.NoError(t, json.Unmarshal(data, &decoded))
			got := decodeAnyValue(&decoded)
			require.NotNil(t, got)
			test.check(t, got)
		})
	}
}
