// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package attribute // import "go.opentelemetry.io/otel/attribute"

import (
	"encoding/base64"
	"fmt"
	"math"
	"reflect"
	"strconv"
	"strings"
)

// KeyValue holds a key and value pair.
type KeyValue struct {
	Key   Key
	Value Value
}

// String returns a string representation of kv using the
// [OpenTelemetry Attribute representation for non-OTLP] rules.
//
// The returned string is a JSON object containing a single key-value pair.
//
// The returned string is meant for debugging;
// the string representation is not stable.
//
// [OpenTelemetry Attribute representation for non-OTLP]: https://opentelemetry.io/docs/specs/otel/common/#attribute-representation-for-non-otlp
func (kv KeyValue) String() string {
	const jsonObjectSyntaxLen = len(`{"":}`)

	var b strings.Builder
	n := len(kv.Key) + jsonObjectSyntaxLen
	switch kv.Value.Type() {
	case BOOL:
		if kv.Value.AsBool() {
			n += len("true")
		} else {
			n += len("false")
		}
	case BOOLSLICE:
		n += jsonArrayBracketsLen
		if l := reflect.ValueOf(kv.Value.slice).Len(); l > 0 {
			n += l*boolArrayElemMaxLen + (l-1)*commaLen
		}
	case INT64:
		var buf [int64ArrayElemMaxLen]byte
		n += len(strconv.AppendInt(buf[:0], kv.Value.AsInt64(), 10))
	case INT64SLICE:
		n += jsonArrayBracketsLen
		if l := reflect.ValueOf(kv.Value.slice).Len(); l > 0 {
			n += l*int64ArrayElemMaxLen + (l-1)*commaLen
		}
	case FLOAT64:
		val := kv.Value.AsFloat64()
		switch {
		case math.IsNaN(val):
			n += len(`"NaN"`)
		case math.IsInf(val, 1):
			n += len(`"Infinity"`)
		case math.IsInf(val, -1):
			n += len(`"-Infinity"`)
		default:
			var buf [float64ArrayElemMaxLen]byte
			n += len(strconv.AppendFloat(buf[:0], val, 'g', -1, 64))
		}
	case FLOAT64SLICE:
		n += jsonArrayBracketsLen
		if l := reflect.ValueOf(kv.Value.slice).Len(); l > 0 {
			n += l*float64ArrayElemMaxLen + (l-1)*commaLen
		}
	case STRING:
		n += len(kv.Value.stringly) + quotesLen
	case STRINGSLICE:
		n += jsonArrayBracketsLen
		if l := reflect.ValueOf(kv.Value.slice).Len(); l > 0 {
			n += l*smallObjectLen + (l-1)*commaLen
		}
	case BYTESLICE:
		n += base64.StdEncoding.EncodedLen(len(kv.Value.stringly)) + quotesLen
	case SLICE:
		n += jsonArrayBracketsLen
		if l := reflect.ValueOf(kv.Value.slice).Len(); l > 0 {
			n += l*smallObjectLen + (l-1)*commaLen
		}
	case EMPTY:
		n += len("null")
	default:
		n += len(`"unknown"`)
	}
	b.Grow(n)

	_ = b.WriteByte('{')
	appendJSONString(&b, string(kv.Key))
	_ = b.WriteByte(':')
	appendJSONValue(&b, kv.Value)
	_ = b.WriteByte('}')
	return b.String()
}

// Valid reports whether kv is a valid OpenTelemetry attribute.
func (kv KeyValue) Valid() bool {
	return kv.Key.Defined()
}

// Bool creates a KeyValue with a BOOL Value type.
func Bool(k string, v bool) KeyValue {
	return Key(k).Bool(v)
}

// BoolSlice creates a KeyValue with a BOOLSLICE Value type.
func BoolSlice(k string, v []bool) KeyValue {
	return Key(k).BoolSlice(v)
}

// Int creates a KeyValue with an INT64 Value type.
func Int(k string, v int) KeyValue {
	return Key(k).Int(v)
}

// IntSlice creates a KeyValue with an INT64SLICE Value type.
func IntSlice(k string, v []int) KeyValue {
	return Key(k).IntSlice(v)
}

// Int64 creates a KeyValue with an INT64 Value type.
func Int64(k string, v int64) KeyValue {
	return Key(k).Int64(v)
}

// Int64Slice creates a KeyValue with an INT64SLICE Value type.
func Int64Slice(k string, v []int64) KeyValue {
	return Key(k).Int64Slice(v)
}

// Float64 creates a KeyValue with a FLOAT64 Value type.
func Float64(k string, v float64) KeyValue {
	return Key(k).Float64(v)
}

// Float64Slice creates a KeyValue with a FLOAT64SLICE Value type.
func Float64Slice(k string, v []float64) KeyValue {
	return Key(k).Float64Slice(v)
}

// String creates a KeyValue with a STRING Value type.
func String(k, v string) KeyValue {
	return Key(k).String(v)
}

// StringSlice creates a KeyValue with a STRINGSLICE Value type.
func StringSlice(k string, v []string) KeyValue {
	return Key(k).StringSlice(v)
}

// ByteSlice creates a KeyValue with a BYTESLICE Value type.
func ByteSlice(k string, v []byte) KeyValue {
	return Key(k).ByteSlice(v)
}

// Slice creates a KeyValue with a SLICE Value type.
func Slice(k string, v ...Value) KeyValue {
	return Key(k).Slice(v...)
}

// Stringer creates a new key-value pair with a passed name and a string
// value generated by the passed Stringer interface.
func Stringer(k string, v fmt.Stringer) KeyValue {
	return Key(k).String(v.String())
}
