// Code generated by "go.opentelemetry.io/otel/sdk/resource/internal/schema/gen"; DO NOT EDIT.
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package schema

import (
	ast10 "go.opentelemetry.io/otel/schema/v1.0/ast"
	"go.opentelemetry.io/otel/schema/v1.1/ast"
	"go.opentelemetry.io/otel/schema/v1.1/types"
)

var Schemas = map[string]*ast.Schema{
	"https://opentelemetry.io/schemas/1.21.0": {
		FileFormat: "1.1.0",
		SchemaURL:  "https://opentelemetry.io/schemas/1.21.0",
		Versions: map[types.TelemetryVersion]ast.VersionDef{
			"1.20.0": {},
			"1.21.0": {
				All: ast10.Attributes{
					Changes: []ast10.AttributeChange{
						{
							RenameAttributes: &ast10.RenameAttributes{
								AttributeMap: map[string]string{
									"Bar": "bar",
								},
							},
						},
						{
							RenameAttributes: &ast10.RenameAttributes{
								AttributeMap: map[string]string{
									"foo": "Foo",
								},
							},
						},
					},
				},
				Resources: ast10.Attributes{
					Changes: []ast10.AttributeChange{
						{
							RenameAttributes: &ast10.RenameAttributes{
								AttributeMap: map[string]string{
									"one": "ONE",
									"two": "TWO",
								},
							},
						},
					},
				},
			},
		},
	},
}
