// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opentelemetry/proto/trace/v1/trace.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v11 "go.opentelemetry.io/otel/internal/opentelemetry-proto-gen/common/v1"
	v1 "go.opentelemetry.io/otel/internal/opentelemetry-proto-gen/resource/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SpanKind is the type of span. Can be used to specify additional relationships between spans
// in addition to a parent/child relationship.
type Span_SpanKind int32

const (
	// Unspecified. Do NOT use as default.
	// Implementations MAY assume SpanKind to be INTERNAL when receiving UNSPECIFIED.
	Span_SPAN_KIND_UNSPECIFIED Span_SpanKind = 0
	// Indicates that the span represents an internal operation within an application,
	// as opposed to an operations happening at the boundaries. Default value.
	Span_INTERNAL Span_SpanKind = 1
	// Indicates that the span covers server-side handling of an RPC or other
	// remote network request.
	Span_SERVER Span_SpanKind = 2
	// Indicates that the span describes a request to some remote service.
	Span_CLIENT Span_SpanKind = 3
	// Indicates that the span describes a producer sending a message to a broker.
	// Unlike CLIENT and SERVER, there is often no direct critical path latency relationship
	// between producer and consumer spans. A PRODUCER span ends when the message was accepted
	// by the broker while the logical processing of the message might span a much longer time.
	Span_PRODUCER Span_SpanKind = 4
	// Indicates that the span describes consumer receiving a message from a broker.
	// Like the PRODUCER kind, there is often no direct critical path latency relationship
	// between producer and consumer spans.
	Span_CONSUMER Span_SpanKind = 5
)

var Span_SpanKind_name = map[int32]string{
	0: "SPAN_KIND_UNSPECIFIED",
	1: "INTERNAL",
	2: "SERVER",
	3: "CLIENT",
	4: "PRODUCER",
	5: "CONSUMER",
}

var Span_SpanKind_value = map[string]int32{
	"SPAN_KIND_UNSPECIFIED": 0,
	"INTERNAL":              1,
	"SERVER":                2,
	"CLIENT":                3,
	"PRODUCER":              4,
	"CONSUMER":              5,
}

func (x Span_SpanKind) String() string {
	return proto.EnumName(Span_SpanKind_name, int32(x))
}

func (Span_SpanKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5c407ac9c675a601, []int{2, 0}
}

// StatusCode mirrors the codes defined at
// https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#statuscanonicalcode
type Status_StatusCode int32

const (
	Status_Ok                 Status_StatusCode = 0
	Status_Cancelled          Status_StatusCode = 1
	Status_UnknownError       Status_StatusCode = 2
	Status_InvalidArgument    Status_StatusCode = 3
	Status_DeadlineExceeded   Status_StatusCode = 4
	Status_NotFound           Status_StatusCode = 5
	Status_AlreadyExists      Status_StatusCode = 6
	Status_PermissionDenied   Status_StatusCode = 7
	Status_ResourceExhausted  Status_StatusCode = 8
	Status_FailedPrecondition Status_StatusCode = 9
	Status_Aborted            Status_StatusCode = 10
	Status_OutOfRange         Status_StatusCode = 11
	Status_Unimplemented      Status_StatusCode = 12
	Status_InternalError      Status_StatusCode = 13
	Status_Unavailable        Status_StatusCode = 14
	Status_DataLoss           Status_StatusCode = 15
	Status_Unauthenticated    Status_StatusCode = 16
)

var Status_StatusCode_name = map[int32]string{
	0:  "Ok",
	1:  "Cancelled",
	2:  "UnknownError",
	3:  "InvalidArgument",
	4:  "DeadlineExceeded",
	5:  "NotFound",
	6:  "AlreadyExists",
	7:  "PermissionDenied",
	8:  "ResourceExhausted",
	9:  "FailedPrecondition",
	10: "Aborted",
	11: "OutOfRange",
	12: "Unimplemented",
	13: "InternalError",
	14: "Unavailable",
	15: "DataLoss",
	16: "Unauthenticated",
}

var Status_StatusCode_value = map[string]int32{
	"Ok":                 0,
	"Cancelled":          1,
	"UnknownError":       2,
	"InvalidArgument":    3,
	"DeadlineExceeded":   4,
	"NotFound":           5,
	"AlreadyExists":      6,
	"PermissionDenied":   7,
	"ResourceExhausted":  8,
	"FailedPrecondition": 9,
	"Aborted":            10,
	"OutOfRange":         11,
	"Unimplemented":      12,
	"InternalError":      13,
	"Unavailable":        14,
	"DataLoss":           15,
	"Unauthenticated":    16,
}

func (x Status_StatusCode) String() string {
	return proto.EnumName(Status_StatusCode_name, int32(x))
}

func (Status_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5c407ac9c675a601, []int{3, 0}
}

// A collection of InstrumentationLibrarySpans from a Resource.
type ResourceSpans struct {
	// The resource for the spans in this message.
	// If this field is not set then no resource info is known.
	Resource *v1.Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// A list of InstrumentationLibrarySpans that originate from a resource.
	InstrumentationLibrarySpans []*InstrumentationLibrarySpans `protobuf:"bytes,2,rep,name=instrumentation_library_spans,json=instrumentationLibrarySpans,proto3" json:"instrumentation_library_spans,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                       `json:"-"`
	XXX_unrecognized            []byte                         `json:"-"`
	XXX_sizecache               int32                          `json:"-"`
}

func (m *ResourceSpans) Reset()         { *m = ResourceSpans{} }
func (m *ResourceSpans) String() string { return proto.CompactTextString(m) }
func (*ResourceSpans) ProtoMessage()    {}
func (*ResourceSpans) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c407ac9c675a601, []int{0}
}

func (m *ResourceSpans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceSpans.Unmarshal(m, b)
}
func (m *ResourceSpans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceSpans.Marshal(b, m, deterministic)
}
func (m *ResourceSpans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceSpans.Merge(m, src)
}
func (m *ResourceSpans) XXX_Size() int {
	return xxx_messageInfo_ResourceSpans.Size(m)
}
func (m *ResourceSpans) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceSpans.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceSpans proto.InternalMessageInfo

func (m *ResourceSpans) GetResource() *v1.Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ResourceSpans) GetInstrumentationLibrarySpans() []*InstrumentationLibrarySpans {
	if m != nil {
		return m.InstrumentationLibrarySpans
	}
	return nil
}

// A collection of Spans produced by an InstrumentationLibrary.
type InstrumentationLibrarySpans struct {
	// The instrumentation library information for the spans in this message.
	// If this field is not set then no library info is known.
	InstrumentationLibrary *v11.InstrumentationLibrary `protobuf:"bytes,1,opt,name=instrumentation_library,json=instrumentationLibrary,proto3" json:"instrumentation_library,omitempty"`
	// A list of Spans that originate from an instrumentation library.
	Spans                []*Span  `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstrumentationLibrarySpans) Reset()         { *m = InstrumentationLibrarySpans{} }
func (m *InstrumentationLibrarySpans) String() string { return proto.CompactTextString(m) }
func (*InstrumentationLibrarySpans) ProtoMessage()    {}
func (*InstrumentationLibrarySpans) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c407ac9c675a601, []int{1}
}

func (m *InstrumentationLibrarySpans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentationLibrarySpans.Unmarshal(m, b)
}
func (m *InstrumentationLibrarySpans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentationLibrarySpans.Marshal(b, m, deterministic)
}
func (m *InstrumentationLibrarySpans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentationLibrarySpans.Merge(m, src)
}
func (m *InstrumentationLibrarySpans) XXX_Size() int {
	return xxx_messageInfo_InstrumentationLibrarySpans.Size(m)
}
func (m *InstrumentationLibrarySpans) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentationLibrarySpans.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentationLibrarySpans proto.InternalMessageInfo

func (m *InstrumentationLibrarySpans) GetInstrumentationLibrary() *v11.InstrumentationLibrary {
	if m != nil {
		return m.InstrumentationLibrary
	}
	return nil
}

func (m *InstrumentationLibrarySpans) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

// Span represents a single operation within a trace. Spans can be
// nested to form a trace tree. Spans may also be linked to other spans
// from the same or different trace and form graphs. Often, a trace
// contains a root span that describes the end-to-end latency, and one
// or more subspans for its sub-operations. A trace can also contain
// multiple root spans, or none at all. Spans do not need to be
// contiguous - there may be gaps or overlaps between spans in a trace.
//
// The next available field id is 17.
type Span struct {
	// A unique identifier for a trace. All spans from the same trace share
	// the same `trace_id`. The ID is a 16-byte array. An ID with all zeroes
	// is considered invalid.
	//
	// This field is semantically required. Receiver should generate new
	// random trace_id if empty or invalid trace_id was received.
	//
	// This field is required.
	TraceId []byte `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// A unique identifier for a span within a trace, assigned when the span
	// is created. The ID is an 8-byte array. An ID with all zeroes is considered
	// invalid.
	//
	// This field is semantically required. Receiver should generate new
	// random span_id if empty or invalid span_id was received.
	//
	// This field is required.
	SpanId []byte `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// trace_state conveys information about request position in multiple distributed tracing graphs.
	// It is a trace_state in w3c-trace-context format: https://www.w3.org/TR/trace-context/#tracestate-header
	// See also https://github.com/w3c/distributed-tracing for more details about this field.
	TraceState string `protobuf:"bytes,3,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	// The `span_id` of this span's parent span. If this is a root span, then this
	// field must be empty. The ID is an 8-byte array.
	ParentSpanId []byte `protobuf:"bytes,4,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	// A description of the span's operation.
	//
	// For example, the name can be a qualified method name or a file name
	// and a line number where the operation is called. A best practice is to use
	// the same display name at the same call point in an application.
	// This makes it easier to correlate spans in different traces.
	//
	// This field is semantically required to be set to non-empty string.
	// When null or empty string received - receiver may use string "name"
	// as a replacement. There might be smarted algorithms implemented by
	// receiver to fix the empty span name.
	//
	// This field is required.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Distinguishes between spans generated in a particular context. For example,
	// two spans with the same name may be distinguished using `CLIENT` (caller)
	// and `SERVER` (callee) to identify queueing latency associated with the span.
	Kind Span_SpanKind `protobuf:"varint,6,opt,name=kind,proto3,enum=opentelemetry.proto.trace.v1.Span_SpanKind" json:"kind,omitempty"`
	// start_time_unix_nano is the start time of the span. On the client side, this is the time
	// kept by the local machine where the span execution starts. On the server side, this
	// is the time when the server's application handler starts running.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// This field is semantically required and it is expected that end_time >= start_time.
	StartTimeUnixNano uint64 `protobuf:"fixed64,7,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	// end_time_unix_nano is the end time of the span. On the client side, this is the time
	// kept by the local machine where the span execution ends. On the server side, this
	// is the time when the server application handler stops running.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// This field is semantically required and it is expected that end_time >= start_time.
	EndTimeUnixNano uint64 `protobuf:"fixed64,8,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"end_time_unix_nano,omitempty"`
	// attributes is a collection of key/value pairs. The value can be a string,
	// an integer, a double or the Boolean values `true` or `false`. Note, global attributes
	// like server name can be set using the resource API. Examples of attributes:
	//
	//     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
	//     "/http/server_latency": 300
	//     "abc.com/myattribute": true
	//     "abc.com/score": 10.239
	Attributes []*v11.KeyValue `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// dropped_attributes_count is the number of attributes that were discarded. Attributes
	// can be discarded because their keys are too long or because there are too many
	// attributes. If this value is 0, then no attributes were dropped.
	DroppedAttributesCount uint32 `protobuf:"varint,10,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
	// events is a collection of Event items.
	Events []*Span_Event `protobuf:"bytes,11,rep,name=events,proto3" json:"events,omitempty"`
	// dropped_events_count is the number of dropped events. If the value is 0, then no
	// events were dropped.
	DroppedEventsCount uint32 `protobuf:"varint,12,opt,name=dropped_events_count,json=droppedEventsCount,proto3" json:"dropped_events_count,omitempty"`
	// links is a collection of Links, which are references from this span to a span
	// in the same or different trace.
	Links []*Span_Link `protobuf:"bytes,13,rep,name=links,proto3" json:"links,omitempty"`
	// dropped_links_count is the number of dropped links after the maximum size was
	// enforced. If this value is 0, then no links were dropped.
	DroppedLinksCount uint32 `protobuf:"varint,14,opt,name=dropped_links_count,json=droppedLinksCount,proto3" json:"dropped_links_count,omitempty"`
	// An optional final status for this span. Semantically when Status
	// wasn't set it is means span ended without errors and assume
	// Status.Ok (code = 0).
	Status               *Status  `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c407ac9c675a601, []int{2}
}

func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (m *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(m, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetTraceId() []byte {
	if m != nil {
		return m.TraceId
	}
	return nil
}

func (m *Span) GetSpanId() []byte {
	if m != nil {
		return m.SpanId
	}
	return nil
}

func (m *Span) GetTraceState() string {
	if m != nil {
		return m.TraceState
	}
	return ""
}

func (m *Span) GetParentSpanId() []byte {
	if m != nil {
		return m.ParentSpanId
	}
	return nil
}

func (m *Span) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span) GetKind() Span_SpanKind {
	if m != nil {
		return m.Kind
	}
	return Span_SPAN_KIND_UNSPECIFIED
}

func (m *Span) GetStartTimeUnixNano() uint64 {
	if m != nil {
		return m.StartTimeUnixNano
	}
	return 0
}

func (m *Span) GetEndTimeUnixNano() uint64 {
	if m != nil {
		return m.EndTimeUnixNano
	}
	return 0
}

func (m *Span) GetAttributes() []*v11.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Span) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

func (m *Span) GetEvents() []*Span_Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Span) GetDroppedEventsCount() uint32 {
	if m != nil {
		return m.DroppedEventsCount
	}
	return 0
}

func (m *Span) GetLinks() []*Span_Link {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Span) GetDroppedLinksCount() uint32 {
	if m != nil {
		return m.DroppedLinksCount
	}
	return 0
}

func (m *Span) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// Event is a time-stamped annotation of the span, consisting of user-supplied
// text description and key-value pairs.
type Span_Event struct {
	// time_unix_nano is the time the event occurred.
	TimeUnixNano uint64 `protobuf:"fixed64,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	// name of the event.
	// This field is semantically required to be set to non-empty string.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// attributes is a collection of attribute key/value pairs on the event.
	Attributes []*v11.KeyValue `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// dropped_attributes_count is the number of dropped attributes. If the value is 0,
	// then no attributes were dropped.
	DroppedAttributesCount uint32   `protobuf:"varint,4,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Span_Event) Reset()         { *m = Span_Event{} }
func (m *Span_Event) String() string { return proto.CompactTextString(m) }
func (*Span_Event) ProtoMessage()    {}
func (*Span_Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c407ac9c675a601, []int{2, 0}
}

func (m *Span_Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span_Event.Unmarshal(m, b)
}
func (m *Span_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span_Event.Marshal(b, m, deterministic)
}
func (m *Span_Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span_Event.Merge(m, src)
}
func (m *Span_Event) XXX_Size() int {
	return xxx_messageInfo_Span_Event.Size(m)
}
func (m *Span_Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Span_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Span_Event proto.InternalMessageInfo

func (m *Span_Event) GetTimeUnixNano() uint64 {
	if m != nil {
		return m.TimeUnixNano
	}
	return 0
}

func (m *Span_Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span_Event) GetAttributes() []*v11.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Span_Event) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

// A pointer from the current span to another span in the same trace or in a
// different trace. For example, this can be used in batching operations,
// where a single batch handler processes multiple requests from different
// traces or when the handler receives a request from a different project.
type Span_Link struct {
	// A unique identifier of a trace that this linked span is part of. The ID is a
	// 16-byte array.
	TraceId []byte `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// A unique identifier for the linked span. The ID is an 8-byte array.
	SpanId []byte `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// The trace_state associated with the link.
	TraceState string `protobuf:"bytes,3,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	// attributes is a collection of attribute key/value pairs on the link.
	Attributes []*v11.KeyValue `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// dropped_attributes_count is the number of dropped attributes. If the value is 0,
	// then no attributes were dropped.
	DroppedAttributesCount uint32   `protobuf:"varint,5,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Span_Link) Reset()         { *m = Span_Link{} }
func (m *Span_Link) String() string { return proto.CompactTextString(m) }
func (*Span_Link) ProtoMessage()    {}
func (*Span_Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c407ac9c675a601, []int{2, 1}
}

func (m *Span_Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span_Link.Unmarshal(m, b)
}
func (m *Span_Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span_Link.Marshal(b, m, deterministic)
}
func (m *Span_Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span_Link.Merge(m, src)
}
func (m *Span_Link) XXX_Size() int {
	return xxx_messageInfo_Span_Link.Size(m)
}
func (m *Span_Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Span_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Span_Link proto.InternalMessageInfo

func (m *Span_Link) GetTraceId() []byte {
	if m != nil {
		return m.TraceId
	}
	return nil
}

func (m *Span_Link) GetSpanId() []byte {
	if m != nil {
		return m.SpanId
	}
	return nil
}

func (m *Span_Link) GetTraceState() string {
	if m != nil {
		return m.TraceState
	}
	return ""
}

func (m *Span_Link) GetAttributes() []*v11.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Span_Link) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

// The Status type defines a logical error model that is suitable for different
// programming environments, including REST APIs and RPC APIs.
type Status struct {
	// The status code. This is optional field. It is safe to assume 0 (OK)
	// when not set.
	Code Status_StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=opentelemetry.proto.trace.v1.Status_StatusCode" json:"code,omitempty"`
	// A developer-facing human readable error message.
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c407ac9c675a601, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() Status_StatusCode {
	if m != nil {
		return m.Code
	}
	return Status_Ok
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("opentelemetry.proto.trace.v1.Span_SpanKind", Span_SpanKind_name, Span_SpanKind_value)
	proto.RegisterEnum("opentelemetry.proto.trace.v1.Status_StatusCode", Status_StatusCode_name, Status_StatusCode_value)
	proto.RegisterType((*ResourceSpans)(nil), "opentelemetry.proto.trace.v1.ResourceSpans")
	proto.RegisterType((*InstrumentationLibrarySpans)(nil), "opentelemetry.proto.trace.v1.InstrumentationLibrarySpans")
	proto.RegisterType((*Span)(nil), "opentelemetry.proto.trace.v1.Span")
	proto.RegisterType((*Span_Event)(nil), "opentelemetry.proto.trace.v1.Span.Event")
	proto.RegisterType((*Span_Link)(nil), "opentelemetry.proto.trace.v1.Span.Link")
	proto.RegisterType((*Status)(nil), "opentelemetry.proto.trace.v1.Status")
}

func init() {
	proto.RegisterFile("opentelemetry/proto/trace/v1/trace.proto", fileDescriptor_5c407ac9c675a601)
}

var fileDescriptor_5c407ac9c675a601 = []byte{
	// 1003 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x6f, 0x1b, 0x37,
	0x13, 0xce, 0xea, 0xdb, 0xa3, 0x0f, 0xaf, 0x99, 0xaf, 0x8d, 0xf3, 0xbe, 0x88, 0x20, 0x04, 0xa8,
	0xda, 0x20, 0x52, 0xed, 0xa2, 0x40, 0x0a, 0xb4, 0x68, 0x65, 0x69, 0x5d, 0x08, 0x76, 0x65, 0x81,
	0xb2, 0x72, 0xe8, 0x65, 0x41, 0x8b, 0xac, 0x42, 0x78, 0x45, 0x0a, 0x5c, 0xae, 0x6a, 0x1f, 0xfa,
	0x7b, 0xfa, 0x2b, 0x7a, 0x2b, 0xd0, 0x5f, 0xd0, 0x6b, 0xef, 0xfd, 0x17, 0x05, 0xb9, 0xbb, 0x8e,
	0x65, 0xd8, 0x72, 0x2e, 0xbe, 0x48, 0xc3, 0x99, 0xe7, 0x99, 0x67, 0x86, 0x33, 0xab, 0x15, 0xb4,
	0xe5, 0x92, 0x09, 0xcd, 0x42, 0xb6, 0x60, 0x5a, 0x5d, 0x76, 0x97, 0x4a, 0x6a, 0xd9, 0xd5, 0x8a,
	0xcc, 0x58, 0x77, 0xb5, 0x97, 0x18, 0x1d, 0xeb, 0x44, 0xff, 0x5b, 0x43, 0x26, 0xce, 0x4e, 0x02,
	0x58, 0xed, 0xed, 0x7e, 0x71, 0x5b, 0x9e, 0x99, 0x5c, 0x2c, 0xa4, 0x30, 0x89, 0x12, 0x2b, 0x21,
	0xed, 0x76, 0x6e, 0xc3, 0x2a, 0x16, 0xc9, 0x58, 0x25, 0xb2, 0x99, 0x9d, 0xe0, 0x5b, 0x7f, 0x3b,
	0x50, 0xc7, 0xa9, 0x6b, 0xb2, 0x24, 0x22, 0x42, 0x3e, 0x54, 0x32, 0x8c, 0xe7, 0x34, 0x9d, 0x76,
	0x75, 0xff, 0xf3, 0xce, 0x6d, 0xe5, 0x5d, 0x25, 0x5a, 0xed, 0x75, 0xb2, 0x0c, 0xf8, 0x8a, 0x8a,
	0x7e, 0x83, 0xff, 0x73, 0x11, 0x69, 0x15, 0x2f, 0x98, 0xd0, 0x44, 0x73, 0x29, 0x82, 0x90, 0x9f,
	0x29, 0xa2, 0x2e, 0x83, 0xc8, 0xe8, 0x78, 0xb9, 0x66, 0xbe, 0x5d, 0xdd, 0xff, 0xa6, 0xb3, 0xa9,
	0xf5, 0xce, 0x70, 0x3d, 0xc5, 0x71, 0x92, 0xc1, 0x16, 0x8a, 0x5f, 0xf2, 0xbb, 0x83, 0xad, 0xbf,
	0x1c, 0x78, 0xb9, 0x81, 0x8c, 0x04, 0x3c, 0xbf, 0xa3, 0xbc, 0xb4, 0xe9, 0xaf, 0x6f, 0x2d, 0x2c,
	0xbd, 0xeb, 0x3b, 0x2b, 0xc3, 0xcf, 0x6e, 0x2f, 0x0a, 0xbd, 0x83, 0xe2, 0xf5, 0xb6, 0x5b, 0x9b,
	0xdb, 0x36, 0x35, 0xe2, 0x84, 0xd0, 0xfa, 0x77, 0x0b, 0x0a, 0xe6, 0x8c, 0x5e, 0x40, 0xc5, 0x02,
	0x02, 0x4e, 0x6d, 0x8d, 0x35, 0x5c, 0xb6, 0xe7, 0x21, 0x45, 0xcf, 0xa1, 0x6c, 0xc0, 0x26, 0x92,
	0xb3, 0x91, 0x92, 0x39, 0x0e, 0x29, 0x7a, 0x05, 0xd5, 0x84, 0x13, 0x69, 0xa2, 0x99, 0x97, 0x6f,
	0x3a, 0xed, 0x2d, 0x0c, 0xd6, 0x35, 0x31, 0x1e, 0xf4, 0x1a, 0x1a, 0x4b, 0xa2, 0x98, 0xd0, 0x41,
	0x96, 0xa0, 0x60, 0x13, 0xd4, 0x12, 0xef, 0x24, 0x49, 0x83, 0xa0, 0x20, 0xc8, 0x82, 0x79, 0x45,
	0xcb, 0xb7, 0x36, 0xfa, 0x1e, 0x0a, 0xe7, 0x5c, 0x50, 0xaf, 0xd4, 0x74, 0xda, 0x8d, 0xfd, 0x37,
	0xf7, 0x37, 0x64, 0x3f, 0x8e, 0xb8, 0xa0, 0xd8, 0x12, 0x51, 0x17, 0x9e, 0x44, 0x9a, 0x28, 0x1d,
	0x68, 0xbe, 0x60, 0x41, 0x2c, 0xf8, 0x45, 0x20, 0x88, 0x90, 0x5e, 0xb9, 0xe9, 0xb4, 0x4b, 0x78,
	0xc7, 0xc6, 0x4e, 0xf9, 0x82, 0x4d, 0x05, 0xbf, 0x18, 0x11, 0x21, 0xd1, 0x1b, 0x40, 0x4c, 0xd0,
	0x9b, 0xf0, 0x8a, 0x85, 0x6f, 0x33, 0x41, 0xd7, 0xc0, 0x3f, 0x02, 0x10, 0xad, 0x15, 0x3f, 0x8b,
	0x35, 0x8b, 0xbc, 0x2d, 0x7b, 0xeb, 0x9f, 0xdd, 0x33, 0xd3, 0x23, 0x76, 0xf9, 0x9e, 0x84, 0x31,
	0xc3, 0xd7, 0xa8, 0xe8, 0x1d, 0x78, 0x54, 0xc9, 0xe5, 0x92, 0xd1, 0xe0, 0xa3, 0x37, 0x98, 0xc9,
	0x58, 0x68, 0x0f, 0x9a, 0x4e, 0xbb, 0x8e, 0x9f, 0xa5, 0xf1, 0xde, 0x55, 0xb8, 0x6f, 0xa2, 0xe8,
	0x07, 0x28, 0xb1, 0x15, 0x13, 0x3a, 0xf2, 0xaa, 0x56, 0xbe, 0xfd, 0x09, 0x77, 0xe4, 0x1b, 0x02,
	0x4e, 0x79, 0xe8, 0x4b, 0x78, 0x92, 0x69, 0x27, 0x9e, 0x54, 0xb7, 0x66, 0x75, 0x51, 0x1a, 0xb3,
	0x9c, 0x54, 0xf3, 0x3b, 0x28, 0x86, 0x5c, 0x9c, 0x47, 0x5e, 0x7d, 0x43, 0xc7, 0xeb, 0x92, 0xc7,
	0x5c, 0x9c, 0xe3, 0x84, 0x85, 0x3a, 0xf0, 0x38, 0x13, 0xb4, 0x8e, 0x54, 0xaf, 0x61, 0xf5, 0x76,
	0xd2, 0x90, 0x21, 0xa4, 0x72, 0xdf, 0x42, 0xc9, 0x6c, 0x56, 0x1c, 0x79, 0xdb, 0xf6, 0xa9, 0x79,
	0x7d, 0x8f, 0x9e, 0xc5, 0xe2, 0x94, 0xb3, 0xfb, 0xa7, 0x03, 0x45, 0x5b, 0xbc, 0x59, 0xc3, 0x1b,
	0x63, 0x75, 0xec, 0x58, 0x6b, 0xfa, 0xfa, 0x4c, 0xb3, 0x35, 0xcc, 0x5d, 0x5b, 0xc3, 0xf5, 0x39,
	0xe7, 0x1f, 0x66, 0xce, 0x85, 0x4d, 0x73, 0xde, 0xfd, 0xc7, 0x81, 0x82, 0xb9, 0x93, 0x87, 0x79,
	0x42, 0xd7, 0x1b, 0x2c, 0x3c, 0x4c, 0x83, 0xc5, 0x4d, 0x0d, 0xb6, 0xe6, 0x50, 0xc9, 0x9e, 0x5d,
	0xf4, 0x02, 0x9e, 0x4e, 0xc6, 0xbd, 0x51, 0x70, 0x34, 0x1c, 0x0d, 0x82, 0xe9, 0x68, 0x32, 0xf6,
	0xfb, 0xc3, 0xc3, 0xa1, 0x3f, 0x70, 0x1f, 0xa1, 0x1a, 0x54, 0x86, 0xa3, 0x53, 0x1f, 0x8f, 0x7a,
	0xc7, 0xae, 0x83, 0x00, 0x4a, 0x13, 0x1f, 0xbf, 0xf7, 0xb1, 0x9b, 0x33, 0x76, 0xff, 0x78, 0xe8,
	0x8f, 0x4e, 0xdd, 0xbc, 0x41, 0x8d, 0xf1, 0xc9, 0x60, 0xda, 0xf7, 0xb1, 0x5b, 0x30, 0xa7, 0xfe,
	0xc9, 0x68, 0x32, 0xfd, 0xc9, 0xc7, 0x6e, 0xb1, 0xf5, 0x7b, 0x1e, 0x4a, 0xc9, 0x8e, 0xa0, 0x3e,
	0x14, 0x66, 0x92, 0x26, 0xaf, 0xa0, 0xc6, 0x7e, 0xf7, 0x53, 0xf6, 0x2a, 0xfd, 0xea, 0x4b, 0xca,
	0xb0, 0x25, 0x23, 0x0f, 0xca, 0x0b, 0x16, 0x45, 0x64, 0x9e, 0xed, 0x4c, 0x76, 0x6c, 0xfd, 0x91,
	0x03, 0xf8, 0x08, 0x47, 0x25, 0xc8, 0x9d, 0x9c, 0xbb, 0x8f, 0x50, 0x1d, 0xb6, 0xfa, 0x44, 0xcc,
	0x58, 0x18, 0x32, 0xea, 0x3a, 0xc8, 0x85, 0xda, 0x54, 0x9c, 0x0b, 0xf9, 0xab, 0xf0, 0x95, 0x92,
	0xca, 0xcd, 0xa1, 0xc7, 0xb0, 0x3d, 0x14, 0x2b, 0x12, 0x72, 0xda, 0x53, 0x73, 0xfb, 0x33, 0xef,
	0xe6, 0xd1, 0x13, 0x70, 0x07, 0x8c, 0xd0, 0x90, 0x0b, 0xe6, 0x5f, 0xcc, 0x18, 0xa3, 0x8c, 0x26,
	0xad, 0x8d, 0xa4, 0x3e, 0x94, 0xb1, 0xa0, 0x6e, 0x11, 0xed, 0x40, 0xbd, 0x17, 0x2a, 0x46, 0xe8,
	0xa5, 0x7f, 0xc1, 0x23, 0x1d, 0xb9, 0x25, 0x43, 0x1b, 0x33, 0xb5, 0xe0, 0x51, 0xc4, 0xa5, 0x18,
	0x30, 0xc1, 0x19, 0x75, 0xcb, 0xe8, 0x29, 0xec, 0x64, 0xaf, 0x53, 0xff, 0xe2, 0x03, 0x89, 0x23,
	0xcd, 0xa8, 0x5b, 0x41, 0xcf, 0x00, 0x1d, 0x12, 0x1e, 0x32, 0x3a, 0x56, 0x6c, 0x26, 0x05, 0xe5,
	0xe6, 0xed, 0xe2, 0x6e, 0xa1, 0x2a, 0x94, 0x7b, 0x67, 0x52, 0x19, 0x10, 0xa0, 0x06, 0xc0, 0x49,
	0xac, 0x4f, 0x7e, 0xc1, 0x44, 0xcc, 0x99, 0x5b, 0x35, 0xa2, 0x53, 0xc1, 0x17, 0x4b, 0x73, 0x6d,
	0xc2, 0x40, 0x6a, 0xc6, 0x35, 0x14, 0x9a, 0x29, 0x41, 0xc2, 0xa4, 0xa7, 0x3a, 0xda, 0x86, 0xea,
	0x54, 0x90, 0x15, 0xe1, 0x21, 0x39, 0x0b, 0x99, 0xdb, 0x30, 0x95, 0x0f, 0x88, 0x26, 0xc7, 0x32,
	0x8a, 0xdc, 0x6d, 0xd3, 0xf2, 0x54, 0x90, 0x58, 0x7f, 0x60, 0x42, 0xf3, 0x19, 0x31, 0x69, 0xdc,
	0x83, 0x08, 0x5e, 0x71, 0xb9, 0x71, 0x28, 0x07, 0x70, 0x6a, 0xac, 0xb1, 0x71, 0x8e, 0x9d, 0x9f,
	0x0f, 0xe6, 0x37, 0xe1, 0x5c, 0x76, 0xa5, 0x66, 0x61, 0x97, 0xa7, 0xe5, 0x74, 0xd7, 0xc2, 0x6f,
	0x6d, 0xb6, 0xb7, 0x73, 0x26, 0xae, 0xfe, 0x32, 0x9d, 0x95, 0xac, 0xef, 0xab, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0x41, 0x9d, 0xfb, 0x59, 0x09, 0x00, 0x00,
}
