// Code generated by "stringer -type=Kind,ValueKind"; DO NOT EDIT.

package metric

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[CounterKind-1]
	_ = x[GaugeKind-2]
	_ = x[MeasureKind-3]
}

const _Kind_name = "InvalidCounterKindGaugeKindMeasureKind"

var _Kind_index = [...]uint8{0, 7, 18, 27, 38}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Int64ValueKind-0]
	_ = x[Float64ValueKind-1]
}

const _ValueKind_name = "Int64ValueKindFloat64ValueKind"

var _ValueKind_index = [...]uint8{0, 14, 30}

func (i ValueKind) String() string {
	if i < 0 || i >= ValueKind(len(_ValueKind_index)-1) {
		return "ValueKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueKind_name[_ValueKind_index[i]:_ValueKind_index[i+1]]
}
