// Code generated by gotmpl. DO NOT MODIFY.
// source: internal/shared/attrdedup/dedup.go.tmpl

// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Package attrdedup deduplicates nested attribute MAP values.
package attrdedup // import "go.opentelemetry.io/otel/sdk/internal/attrdedup"

import (
	"reflect"
	"unsafe"

	"go.opentelemetry.io/otel/attribute"
)

var (
	keyValueType = reflect.TypeFor[attribute.KeyValue]()
	valueType    = reflect.TypeFor[attribute.Value]()
)

// rawValue mirrors attribute.Value. It is used only to read immutable slice
// storage without calling AsMap or AsSlice on no-op paths.
type rawValue struct {
	vtype    attribute.Type
	numeric  uint64
	stringly string
	slice    any
}

// Value returns value with all nested MAP values deduplicated.
//
// Duplicate MAP keys are resolved using last-value-wins semantics. If
// allowKeyDuplication is true, value is returned unchanged.
func Value(value attribute.Value, allowKeyDuplication bool) attribute.Value {
	if allowKeyDuplication {
		return value
	}
	value, _ = deduplicateValue(value)
	return value
}

// KeyValue returns kv with all nested MAP values deduplicated.
//
// If allowKeyDuplication is true, kv is returned unchanged.
func KeyValue(kv attribute.KeyValue, allowKeyDuplication bool) attribute.KeyValue {
	if allowKeyDuplication {
		return kv
	}
	kv, _ = deduplicateKeyValue(kv)
	return kv
}

// KeyValues returns kvs with all nested MAP values deduplicated.
//
// The returned slice is the original kvs slice if no value needs
// deduplication. Top-level keys in kvs are not deduplicated.
func KeyValues(kvs []attribute.KeyValue, allowKeyDuplication bool) []attribute.KeyValue {
	if allowKeyDuplication {
		return kvs
	}
	kvs, _ = deduplicateKeyValues(kvs)
	return kvs
}

// Set returns set with all nested MAP values deduplicated.
//
// The returned Set is the original set if no value needs deduplication.
func Set(set attribute.Set, allowKeyDuplication bool) attribute.Set {
	if allowKeyDuplication || set.Len() == 0 {
		return set
	}

	var normalized []attribute.KeyValue
	for i := 0; i < set.Len(); i++ {
		kv, _ := set.Get(i)
		kv, changed := deduplicateKeyValue(kv)
		if normalized != nil {
			normalized = append(normalized, kv)
			continue
		}
		if !changed {
			continue
		}

		normalized = make([]attribute.KeyValue, 0, set.Len())
		for j := 0; j < i; j++ {
			prior, _ := set.Get(j)
			normalized = append(normalized, prior)
		}
		normalized = append(normalized, kv)
	}
	if normalized == nil {
		return set
	}

	return attribute.NewSet(normalized...)
}

func deduplicateKeyValues(kvs []attribute.KeyValue) ([]attribute.KeyValue, bool) {
	var normalized []attribute.KeyValue
	for i, kv := range kvs {
		kv, changed := deduplicateKeyValue(kv)
		if normalized != nil {
			normalized[i] = kv
			continue
		}
		if !changed {
			continue
		}

		normalized = make([]attribute.KeyValue, len(kvs))
		copy(normalized, kvs[:i])
		normalized[i] = kv
	}
	if normalized == nil {
		return kvs, false
	}
	return normalized, true
}

func deduplicateKeyValue(kv attribute.KeyValue) (attribute.KeyValue, bool) {
	value, changed := deduplicateValue(kv.Value)
	if changed {
		kv.Value = value
	}
	return kv, changed
}

func deduplicateValue(value attribute.Value) (attribute.Value, bool) {
	switch value.Type() {
	case attribute.SLICE:
		return deduplicateSliceValue(value)
	case attribute.MAP:
		return deduplicateMapValue(value)
	default:
		return value, false
	}
}

func deduplicateSliceValue(value attribute.Value) (attribute.Value, bool) {
	storage := valueStorage(value)
	length := valueLen(storage)

	var normalized []attribute.Value
	for i := 0; i < length; i++ {
		elem := valueAt(storage, i)
		elem, changed := deduplicateValue(elem)
		if normalized != nil {
			normalized[i] = elem
			continue
		}
		if !changed {
			continue
		}

		normalized = make([]attribute.Value, length)
		for j := 0; j < i; j++ {
			normalized[j] = valueAt(storage, j)
		}
		normalized[i] = elem
	}
	if normalized == nil {
		return value, false
	}
	return attribute.SliceValue(normalized...), true
}

func deduplicateMapValue(value attribute.Value) (attribute.Value, bool) {
	storage := valueStorage(value)
	length := keyValueLen(storage)
	if length <= 1 {
		if length == 1 {
			kv, changed := deduplicateKeyValue(keyValueAt(storage, 0))
			if changed {
				return attribute.MapValue(kv), true
			}
		}
		return value, false
	}

	var normalized []attribute.KeyValue
	for i := 0; i < length; {
		first := keyValueAt(storage, i)
		j := i + 1
		for j < length && keyValueAt(storage, j).Key == first.Key {
			j++
		}

		kv, nestedChanged := deduplicateKeyValue(keyValueAt(storage, j-1))
		changed := nestedChanged || j-i > 1
		if normalized != nil {
			normalized = append(normalized, kv)
		} else if changed {
			normalized = make([]attribute.KeyValue, 0, length)
			for k := 0; k < i; k++ {
				normalized = append(normalized, keyValueAt(storage, k))
			}
			normalized = append(normalized, kv)
		}
		i = j
	}
	if normalized == nil {
		return value, false
	}
	return attribute.MapValue(normalized...), true
}

func valueStorage(value attribute.Value) any {
	return (*rawValue)(unsafe.Pointer(&value)).slice //nolint:gosec // Read-only mirror of attribute.Value for allocation-free iteration.
}

func valueLen(storage any) int {
	switch storage.(type) {
	case [0]attribute.Value:
		return 0
	case [1]attribute.Value:
		return 1
	case [2]attribute.Value:
		return 2
	case [3]attribute.Value:
		return 3
	case [4]attribute.Value:
		return 4
	case [5]attribute.Value:
		return 5
	default:
		return arrayLen(storage, valueType)
	}
}

func valueAt(storage any, i int) attribute.Value {
	switch values := storage.(type) {
	case [1]attribute.Value:
		return values[i]
	case [2]attribute.Value:
		return values[i]
	case [3]attribute.Value:
		return values[i]
	case [4]attribute.Value:
		return values[i]
	case [5]attribute.Value:
		return values[i]
	default:
		return arrayAt[attribute.Value](storage, valueType, i)
	}
}

func keyValueLen(storage any) int {
	switch storage.(type) {
	case [0]attribute.KeyValue:
		return 0
	case [1]attribute.KeyValue:
		return 1
	case [2]attribute.KeyValue:
		return 2
	case [3]attribute.KeyValue:
		return 3
	case [4]attribute.KeyValue:
		return 4
	case [5]attribute.KeyValue:
		return 5
	default:
		return arrayLen(storage, keyValueType)
	}
}

func keyValueAt(storage any, i int) attribute.KeyValue {
	switch kvs := storage.(type) {
	case [1]attribute.KeyValue:
		return kvs[i]
	case [2]attribute.KeyValue:
		return kvs[i]
	case [3]attribute.KeyValue:
		return kvs[i]
	case [4]attribute.KeyValue:
		return kvs[i]
	case [5]attribute.KeyValue:
		return kvs[i]
	default:
		return arrayAt[attribute.KeyValue](storage, keyValueType, i)
	}
}

func arrayLen(storage any, elem reflect.Type) int {
	array := reflect.ValueOf(storage)
	if array.Kind() != reflect.Array || array.Type().Elem() != elem {
		return 0
	}
	return array.Len()
}

func arrayAt[T any](storage any, elem reflect.Type, i int) T {
	array := reflect.ValueOf(storage)
	if array.Kind() != reflect.Array || array.Type().Elem() != elem || i < 0 || i >= array.Len() {
		var zero T
		return zero
	}
	return array.Index(i).Interface().(T)
}
