// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/otlptrace/otlpconfig/zstd.go.tmpl

package otlpconfig

import (
	"io"
	"sync"

	"github.com/klauspost/compress/zstd"
	"google.golang.org/grpc/encoding"
)

// concurrency limits the encoder and decoder to a single internal worker.
// zstd's default is GOMAXPROCS-or-4 background goroutines per instance for
// parallel block encoding/decoding, which mainly pays off on large payloads;
// typical OTLP batches are too small to benefit, and it also bounds the
// goroutines leaked if a pooled *zstd.Decoder is dropped by sync.Pool
// without Close ever being called (zstd.Decoder has no finalizer).
const concurrency = 1

func init() {
	c := &zstdCompressor{}
	c.poolCompressor.New = func() any {
		enc, err := zstd.NewWriter(io.Discard, zstd.WithEncoderConcurrency(concurrency))
		if err != nil {
			panic(err)
		}
		return &zstdWriter{Encoder: enc, pool: &c.poolCompressor}
	}
	encoding.RegisterCompressor(c)
}

// zstdCompressor implements grpc/encoding.Compressor, registered under the
// name "zstd" on import so WithCompression(ZstdCompression) requires no
// separate codec registration by the caller.
type zstdCompressor struct {
	poolCompressor   sync.Pool
	poolDecompressor sync.Pool
}

func (c *zstdCompressor) Compress(w io.Writer) (io.WriteCloser, error) {
	z := c.poolCompressor.Get().(*zstdWriter)
	z.Encoder.Reset(w)
	return z, nil
}

func (c *zstdCompressor) Decompress(r io.Reader) (io.Reader, error) {
	z, inPool := c.poolDecompressor.Get().(*zstdReader)
	if !inPool {
		dec, err := zstd.NewReader(r, zstd.WithDecoderConcurrency(concurrency))
		if err != nil {
			return nil, err
		}
		return &zstdReader{Decoder: dec, pool: &c.poolDecompressor}, nil
	}
	if err := z.Reset(r); err != nil {
		// The decoder is left unusable by a failed Reset, so it must not
		// return to the pool.
		return nil, err
	}
	return z, nil
}

func (c *zstdCompressor) Name() string { return "zstd" }

type zstdWriter struct {
	*zstd.Encoder
	pool *sync.Pool
}

// zstd.Encoder is documented as reusable after Close, unlike zstd.Decoder
// below.
func (z *zstdWriter) Close() error {
	defer z.pool.Put(z)
	return z.Encoder.Close()
}

type zstdReader struct {
	*zstd.Decoder
	pool *sync.Pool
}

// Close returns the decoder to the pool without calling zstd.Decoder.Close,
// which frees it permanently; zstd.Decoder.Reset is the documented way to
// reuse one for a new stream.
func (z *zstdReader) Close() error {
	z.pool.Put(z)
	return nil
}
