// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/otlpmetric/oconf/zstd_test.go.tmpl

//go:build !nozstd

package oconf

import (
	"bytes"
	"io"
	"testing"

	"github.com/klauspost/compress/zstd"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc/encoding"
)

func TestZstdCompressorRoundTrip(t *testing.T) {
	c := encoding.GetCompressor("zstd")
	require.NotNil(t, c, "zstd compressor must be registered by this package's init")

	want := []byte("otlp export payload used to exercise the zstd codec")

	var compressed bytes.Buffer
	wc, err := c.Compress(&compressed)
	require.NoError(t, err)
	_, err = wc.Write(want)
	require.NoError(t, err)
	require.NoError(t, wc.Close())

	// The OTEP's frame profile requires the window, when present, to be
	// capped at 8 MB per RFC 9659 §3's HTTP interoperability recommendation.
	var hdr zstd.Header
	require.NoError(t, hdr.Decode(compressed.Bytes()))
	if !hdr.SingleSegment {
		assert.LessOrEqual(
			t, hdr.WindowSize, uint64(maxWindowSize),
			"zstd window size must not exceed the OTEP's 8 MB cap",
		)
	}
	assert.Zero(t, hdr.DictionaryID, "OTLP zstd frames must not use a dictionary")

	r, err := c.Decompress(bytes.NewReader(compressed.Bytes()))
	require.NoError(t, err)
	got, err := io.ReadAll(r)
	require.NoError(t, err)
	assert.Equal(t, want, got)
}

func TestZstdCompressorName(t *testing.T) {
	c := encoding.GetCompressor("zstd")
	require.NotNil(t, c)
	assert.Equal(t, "zstd", c.Name())
}
