# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: otel-collector
  name: otel-collector
  namespace: observability
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - observability
  selector:
    matchLabels:
      app: opentelemetry
