// Code generated by "stringer -type=AggregationTemporality"; DO NOT EDIT.

package metric

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CumulativeAggregationTemporality-1]
	_ = x[DeltaAggregationTemporality-2]
}

const _AggregationTemporality_name = "CumulativeAggregationTemporalityDeltaAggregationTemporality"

var _AggregationTemporality_index = [...]uint8{0, 32, 59}

func (i AggregationTemporality) String() string {
	i -= 1
	if i < 0 || i >= AggregationTemporality(len(_AggregationTemporality_index)-1) {
		return "AggregationTemporality(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AggregationTemporality_name[_AggregationTemporality_index[i]:_AggregationTemporality_index[i+1]]
}
