// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/otlpjson/common.go.tmpl

package otlpjson

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
	"strconv"
	"strings"

	commonpb "go.opentelemetry.io/proto/otlp/common/v1"
)

// Resource corresponds to resourcepb.Resource.
type Resource struct {
	Attributes             []*KeyValue  `json:"attributes,omitempty"`
	DroppedAttributesCount uint32       `json:"droppedAttributesCount,omitempty"`
	EntityRefs             []*EntityRef `json:"entityRefs,omitempty"`
}

// InstrumentationScope corresponds to commonpb.InstrumentationScope.
type InstrumentationScope struct {
	Name                   string      `json:"name,omitempty"`
	Version                string      `json:"version,omitempty"`
	Attributes             []*KeyValue `json:"attributes,omitempty"`
	DroppedAttributesCount uint32      `json:"droppedAttributesCount,omitempty"`
}

// EntityRef corresponds to commonpb.EntityRef.
type EntityRef struct {
	SchemaURL       string   `json:"schemaUrl,omitempty"`
	Type            string   `json:"type,omitempty"`
	IdKeys          []string `json:"idKeys,omitempty"`
	DescriptionKeys []string `json:"descriptionKeys,omitempty"`
}

// KeyValue corresponds to commonpb.KeyValue.
type KeyValue struct {
	Key   string    `json:"key"`
	Value *AnyValue `json:"value,omitempty"`
}

// AnyValue corresponds to commonpb.AnyValue.
type AnyValue struct {
	StringValue *string      `json:"stringValue,omitempty"`
	BoolValue   *bool        `json:"boolValue,omitempty"`
	IntValue    *Int64       `json:"intValue,omitempty"`
	DoubleValue *Float64     `json:"doubleValue,omitempty"`
	ArrayValue  *ArrayValue  `json:"arrayValue,omitempty"`
	KvlistValue *KvlistValue `json:"kvlistValue,omitempty"`
	// BytesValue is a pointer so a selected empty byte value serializes as
	// {"bytesValue":""} instead of being dropped by omitempty.
	BytesValue *[]byte `json:"bytesValue,omitempty"`
}

// ArrayValue corresponds to commonpb.ArrayValue.
type ArrayValue struct {
	Values []*AnyValue `json:"values,omitempty"`
}

// KvlistValue corresponds to commonpb.KeyValueList.
type KvlistValue struct {
	Values []*KeyValue `json:"values,omitempty"`
}

// Float64 encodes non-finite values as strings per ProtoJSON specs.
type Float64 float64

// MarshalJSON implements the [json.Marshaler] interface.
func (f Float64) MarshalJSON() ([]byte, error) {
	switch value := float64(f); {
	case math.IsNaN(value):
		return []byte(`"NaN"`), nil
	case math.IsInf(value, 1):
		return []byte(`"Infinity"`), nil
	case math.IsInf(value, -1):
		return []byte(`"-Infinity"`), nil
	default:
		return strconv.AppendFloat(nil, value, 'g', -1, 64), nil
	}
}

// UnmarshalJSON implements the [json.Unmarshaler] interface.
func (f *Float64) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		switch str {
		case "NaN":
			*f = Float64(math.NaN())
		case "Infinity":
			*f = Float64(math.Inf(1))
		case "-Infinity":
			*f = Float64(math.Inf(-1))
		default:
			var value *float64
			if str != strings.TrimSpace(str) || json.Unmarshal([]byte(str), &value) != nil || value == nil {
				return fmt.Errorf("invalid float value %q", str)
			}
			*f = Float64(*value)
		}
		return nil
	}

	var value float64
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = Float64(value)
	return nil
}

// Int64 encodes int64 as a quoted decimal string per ProtoJSON specs.
type Int64 int64

// MarshalJSON implements the [json.Marshaler] interface.
func (i Int64) MarshalJSON() ([]byte, error) {
	return []byte(`"` + strconv.FormatInt(int64(i), 10) + `"`), nil
}

// UnmarshalJSON implements the [json.Unmarshaler] interface.
func (i *Int64) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		v, err := strconv.ParseInt(s, 10, 64)
		if err != nil {
			return err
		}
		*i = Int64(v)
		return nil
	}
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*i = Int64(v)
	return nil
}

// Uint64 encodes uint64 as a quoted decimal string per ProtoJSON specs.
type Uint64 uint64

// MarshalJSON implements the [json.Marshaler] interface.
func (i Uint64) MarshalJSON() ([]byte, error) {
	return []byte(`"` + strconv.FormatUint(uint64(i), 10) + `"`), nil
}

// UnmarshalJSON implements the [json.Unmarshaler] interface.
func (i *Uint64) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		v, err := strconv.ParseUint(s, 10, 64)
		if err != nil {
			return err
		}
		*i = Uint64(v)
		return nil
	}
	var v uint64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*i = Uint64(v)
	return nil
}

const base16Alphabets = "0123456789ABCDEF"

// TraceID encodes a 16-byte trace ID as a case-insensitive hex-encoded string.
type TraceID [16]byte

// MarshalJSON implements the [json.Marshaler] interface.
func (t TraceID) MarshalJSON() ([]byte, error) {
	var b [34]byte
	b[0] = '"'
	for i, v := range t {
		b[1+i*2] = base16Alphabets[v>>4]
		b[2+i*2] = base16Alphabets[v&0x0f]
	}
	b[33] = '"'
	return b[:], nil
}

// UnmarshalJSON implements the [json.Unmarshaler] interface.
func (t *TraceID) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	b, err := hex.DecodeString(str)
	if err != nil {
		return err
	}
	if len(b) != len(t) {
		return fmt.Errorf("invalid trace ID length: got %d, want %d", len(b), len(t))
	}
	copy(t[:], b)
	return nil
}

// SpanID encodes an 8-byte span ID as a case-insensitive hex-encoded string.
type SpanID [8]byte

// MarshalJSON implements the [json.Marshaler] interface.
func (s SpanID) MarshalJSON() ([]byte, error) {
	var b [18]byte
	b[0] = '"'
	for i, v := range s {
		b[1+i*2] = base16Alphabets[v>>4]
		b[2+i*2] = base16Alphabets[v&0x0f]
	}
	b[17] = '"'
	return b[:], nil
}

// UnmarshalJSON implements the [json.Unmarshaler] interface.
func (s *SpanID) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	b, err := hex.DecodeString(str)
	if err != nil {
		return err
	}
	if len(b) != len(s) {
		return fmt.Errorf("invalid span ID length: got %d, want %d", len(b), len(s))
	}
	copy(s[:], b)
	return nil
}

func encodeEntityRefs(ers []*commonpb.EntityRef) []*EntityRef {
	if len(ers) == 0 {
		return nil
	}
	out := make([]*EntityRef, len(ers))
	for i, er := range ers {
		if er == nil {
			continue
		}
		out[i] = &EntityRef{
			SchemaURL:       er.SchemaUrl,
			Type:            er.Type,
			IdKeys:          er.IdKeys,
			DescriptionKeys: er.DescriptionKeys,
		}
	}
	return out
}

func encodeKeyValues(kvs []*commonpb.KeyValue) []*KeyValue {
	if len(kvs) == 0 {
		return nil
	}
	out := make([]*KeyValue, len(kvs))
	for i, kv := range kvs {
		if kv == nil {
			continue
		}
		out[i] = &KeyValue{
			Key:   kv.Key,
			Value: encodeAnyValue(kv.Value),
		}
	}
	return out
}

func encodeAnyValue(av *commonpb.AnyValue) *AnyValue {
	if av == nil {
		return nil
	}
	out := &AnyValue{}
	switch v := av.Value.(type) {
	case *commonpb.AnyValue_StringValue:
		out.StringValue = &v.StringValue
	case *commonpb.AnyValue_BoolValue:
		out.BoolValue = &v.BoolValue
	case *commonpb.AnyValue_IntValue:
		iv := Int64(v.IntValue)
		out.IntValue = &iv
	case *commonpb.AnyValue_DoubleValue:
		dv := Float64(v.DoubleValue)
		out.DoubleValue = &dv
	case *commonpb.AnyValue_ArrayValue:
		if v.ArrayValue != nil {
			arr := &ArrayValue{}
			for _, val := range v.ArrayValue.Values {
				arr.Values = append(arr.Values, encodeAnyValue(val))
			}
			out.ArrayValue = arr
		}
	case *commonpb.AnyValue_KvlistValue:
		if v.KvlistValue != nil {
			out.KvlistValue = &KvlistValue{
				Values: encodeKeyValues(v.KvlistValue.Values),
			}
		}
	case *commonpb.AnyValue_BytesValue:
		// Always allocate so empty selected bytes values remain present on the wire.
		b := append([]byte{}, v.BytesValue...)
		out.BytesValue = &b
	}
	return out
}

func decodeEntityRefs(jers []*EntityRef) []*commonpb.EntityRef {
	if len(jers) == 0 {
		return nil
	}
	ers := make([]*commonpb.EntityRef, len(jers))
	for i, jer := range jers {
		if jer == nil {
			continue
		}
		ers[i] = &commonpb.EntityRef{
			SchemaUrl:       jer.SchemaURL,
			Type:            jer.Type,
			IdKeys:          jer.IdKeys,
			DescriptionKeys: jer.DescriptionKeys,
		}
	}
	return ers
}

func decodeKeyValues(jkvs []*KeyValue) []*commonpb.KeyValue {
	if len(jkvs) == 0 {
		return nil
	}
	kvs := make([]*commonpb.KeyValue, len(jkvs))
	for i, jkv := range jkvs {
		if jkv == nil {
			continue
		}
		kvs[i] = &commonpb.KeyValue{
			Key:   jkv.Key,
			Value: decodeAnyValue(jkv.Value),
		}
	}
	return kvs
}

func decodeAnyValue(jav *AnyValue) *commonpb.AnyValue {
	if jav == nil {
		return nil
	}
	av := &commonpb.AnyValue{}
	switch {
	case jav.StringValue != nil:
		av.Value = &commonpb.AnyValue_StringValue{StringValue: *jav.StringValue}
	case jav.BoolValue != nil:
		av.Value = &commonpb.AnyValue_BoolValue{BoolValue: *jav.BoolValue}
	case jav.IntValue != nil:
		av.Value = &commonpb.AnyValue_IntValue{IntValue: int64(*jav.IntValue)}
	case jav.DoubleValue != nil:
		av.Value = &commonpb.AnyValue_DoubleValue{DoubleValue: float64(*jav.DoubleValue)}
	case jav.ArrayValue != nil:
		arr := &commonpb.ArrayValue{}
		for _, v := range jav.ArrayValue.Values {
			arr.Values = append(arr.Values, decodeAnyValue(v))
		}
		av.Value = &commonpb.AnyValue_ArrayValue{ArrayValue: arr}
	case jav.KvlistValue != nil:
		av.Value = &commonpb.AnyValue_KvlistValue{
			KvlistValue: &commonpb.KeyValueList{
				Values: decodeKeyValues(jav.KvlistValue.Values),
			},
		}
	case jav.BytesValue != nil:
		av.Value = &commonpb.AnyValue_BytesValue{BytesValue: append([]byte(nil), (*jav.BytesValue)...)}
	}
	return av
}
