// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/otlplog/transform/log_attr_test.go.tmpl

package transform

import (
	"testing"

	cpb "go.opentelemetry.io/proto/otlp/common/v1"

	"go.opentelemetry.io/otel/attribute"
)

var (
	logAttrBool    = attribute.Bool("bool", true)
	logAttrInt     = attribute.Int("int", 1)
	logAttrInt64   = attribute.Int64("int64", 1)
	logAttrFloat64 = attribute.Float64("float64", 1)
	logAttrString  = attribute.String("string", "o")
	logAttrBytes   = attribute.ByteSlice("bytes", []byte("test"))
	logAttrSlice   = attribute.Slice("slice", attribute.BoolValue(true))
	logAttrMap     = attribute.Map("map", logAttrString)
	logAttrEmpty   = attribute.KeyValue{Key: "empty"}

	kvBytes = &cpb.KeyValue{
		Key: "bytes",
		Value: &cpb.AnyValue{
			Value: &cpb.AnyValue_BytesValue{
				BytesValue: []byte("test"),
			},
		},
	}
	kvSlice = &cpb.KeyValue{
		Key: "slice",
		Value: &cpb.AnyValue{
			Value: &cpb.AnyValue_ArrayValue{
				ArrayValue: &cpb.ArrayValue{
					Values: []*cpb.AnyValue{valBoolTrue},
				},
			},
		},
	}
	kvMap = &cpb.KeyValue{
		Key: "map",
		Value: &cpb.AnyValue{
			Value: &cpb.AnyValue_KvlistValue{
				KvlistValue: &cpb.KeyValueList{
					Values: []*cpb.KeyValue{kvString},
				},
			},
		},
	}
)

func TestLogAttrs(t *testing.T) {
	type logAttrTest struct {
		name string
		in   []attribute.KeyValue
		want []*cpb.KeyValue
	}

	for _, test := range []logAttrTest{
		{"nil", nil, nil},
		{"len(0)", []attribute.KeyValue{}, nil},
		{
			"empty",
			[]attribute.KeyValue{logAttrEmpty},
			[]*cpb.KeyValue{kvEmpty},
		},
		{
			"bool",
			[]attribute.KeyValue{logAttrBool},
			[]*cpb.KeyValue{kvBool},
		},
		{
			"int",
			[]attribute.KeyValue{logAttrInt},
			[]*cpb.KeyValue{kvInt},
		},
		{
			"int64",
			[]attribute.KeyValue{logAttrInt64},
			[]*cpb.KeyValue{kvInt64},
		},
		{
			"float64",
			[]attribute.KeyValue{logAttrFloat64},
			[]*cpb.KeyValue{kvFloat64},
		},
		{
			"string",
			[]attribute.KeyValue{logAttrString},
			[]*cpb.KeyValue{kvString},
		},
		{
			"bytes",
			[]attribute.KeyValue{logAttrBytes},
			[]*cpb.KeyValue{kvBytes},
		},
		{
			"slice",
			[]attribute.KeyValue{logAttrSlice},
			[]*cpb.KeyValue{kvSlice},
		},
		{
			"map",
			[]attribute.KeyValue{logAttrMap},
			[]*cpb.KeyValue{kvMap},
		},
		{
			"all",
			[]attribute.KeyValue{
				logAttrBool,
				logAttrInt,
				logAttrInt64,
				logAttrFloat64,
				logAttrString,
				logAttrBytes,
				logAttrSlice,
				logAttrMap,
				logAttrEmpty,
			},
			[]*cpb.KeyValue{
				kvBool,
				kvInt,
				kvInt64,
				kvFloat64,
				kvString,
				kvBytes,
				kvSlice,
				kvMap,
				kvEmpty,
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			assertKeyValueSlicesEqual(t, test.want, Attrs(test.in))
		})
	}
}

func TestLogAttrsPreserveDuplicateKeys(t *testing.T) {
	want := []*cpb.KeyValue{
		{Key: "dup", Value: valBoolTrue},
		{Key: "dup", Value: valStrO},
	}

	assertKeyValueSlicesEqual(t, want, Attrs([]attribute.KeyValue{
		attribute.Bool("dup", true),
		attribute.String("dup", "o"),
	}))
}
