// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "./internal/main.go"; DO NOT EDIT.

package unit // import "go.opentelemetry.io/otel/metric/unit"

// Base units.
var (
	// Meter is a base-unit representing length.
	Meter = Unit{code: "m", symbol: "m"}

	// Second is a base-unit representing time.
	Second = Unit{code: "s", symbol: "s"}

	// Gram is a base-unit representing mass.
	Gram = Unit{code: "g", symbol: "g"}

	// Radian is a base-unit representing plane angle.
	Radian = Unit{code: "rad", symbol: "rad"}

	// Kelvin is a base-unit representing temperature.
	Kelvin = Unit{code: "K", symbol: "K"}

	// Coulomb is a base-unit representing electric charge.
	Coulomb = Unit{code: "C", symbol: "C"}

	// Candela is a base-unit representing luminous intensity.
	Candela = Unit{code: "cd", symbol: "cd"}
)
