// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "./internal/main.go"; DO NOT EDIT.

package unit // import "go.opentelemetry.io/otel/metric/unit"

// Metric units.
var (
	// Hertz is a metric unit representing frequency.
	Hertz = Unit{code: "Hz", symbol: "Hz"}

	// Watt is a metric unit representing power.
	Watt = Unit{code: "W", symbol: "W"}

	// Volt is a metric unit representing electric potential.
	Volt = Unit{code: "V", symbol: "V"}

	// DegreeCelsius is a metric unit representing temperature.
	DegreeCelsius = Unit{code: "Cel", symbol: "°C"}

	// Bit is a metric unit representing amount of information.
	Bit = Unit{code: "bit", symbol: "bit"}

	// Byte is a metric unit representing amount of information.
	Byte = Unit{code: "By", symbol: "B"}

	// Baud is a metric unit representing signal transmission rate.
	Baud = Unit{code: "Bd", symbol: "Bd"}
)
