// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

/*
Package log provides the OpenTelemetry Logs SDK.

See https://opentelemetry.io/docs/concepts/signals/logs/ for information
about the concept of OpenTelemetry Logs and
https://opentelemetry.io/docs/concepts/components/ for more information
about OpenTelemetry SDKs.

The entry point for the log package is [NewLoggerProvider].
[LoggerProvider] is the object that all Bridge API calls use to create
Loggers, and ultimately emit log records.
Also, it is an object that should be used to
control the life-cycle (start, flush, and shutdown) of the Logs SDK.

A LoggerProvider needs to be configured to process the log records, this is
done by configuring it with a [Processor] implementation using [WithProcessor].
The log package provides the [BatchProcessor] and [SimpleProcessor]
that are configured with an [Exporter] implementation which
exports the log records to given destination. See
[go.opentelemetry.io/otel/exporters] for exporters that can be used with these
Processors.

The data generated by a LoggerProvider needs to include information about its
origin. A LoggerProvider needs to be configured with a Resource, by using
[WithResource], to include this information. This Resource
should be used to describe the unique runtime environment instrumented code
is being run on. That way when multiple instances of the code are collected
at a single endpoint their origin is decipherable.

# Environment Variables

The following environment variables are used by this package.

OTEL_LOGRECORD_ATTRIBUTE_COUNT_LIMIT (default: 128) and
OTEL_LOGRECORD_ATTRIBUTE_VALUE_LENGTH_LIMIT (default: unlimited) -
configure [NewLoggerProvider] when [WithAttributeCountLimit] or
[WithAttributeValueLengthLimit] are not used.

OTEL_BLRP_MAX_QUEUE_SIZE (default: 2048),
OTEL_BLRP_SCHEDULE_DELAY (default: 1000),
OTEL_BLRP_EXPORT_TIMEOUT (default: 30000), and
OTEL_BLRP_MAX_EXPORT_BATCH_SIZE (default: 512) -
configure [NewBatchProcessor] when [WithMaxQueueSize],
[WithExportInterval], [WithExportTimeout], or [WithExportMaxBatchSize] are
not used. The duration values are interpreted as milliseconds.

Resource-related environment variables, including OTEL_RESOURCE_ATTRIBUTES and
OTEL_SERVICE_NAME, are documented in
[go.opentelemetry.io/otel/sdk/resource] and are applied when this package uses
the default resource or
[WithResource].

See [go.opentelemetry.io/otel/sdk/log/internal/x] for information about
the experimental features.

See [go.opentelemetry.io/otel/log] for more information about
the OpenTelemetry Logs API.
*/
package log
