name: Benchmark
on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'Makefile'
      - '.github/workflows/benchmark.yml'
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

env:
  DEFAULT_GO_VERSION: "~1.26.0"
jobs:
  # Related issue: https://github.com/CodSpeedHQ/codspeed-go/issues/51
  sharding-benchmark:
    name: Sharding benchmarks
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.sharding.outputs.shards }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: sharding
        run: |
          echo "shards=$(make print-sharded-benchmarks)" >> $GITHUB_OUTPUT

  benchmark:
    needs: sharding-benchmark
    permissions:
      contents: write # required for pushing to gh-pages branch
    name: Benchmarks
    runs-on: oracle-bare-metal-64cpu-1024gb-x86-64-ubuntu-24
    strategy:
      matrix:
        shard: ${{ fromJson(needs.sharding-benchmark.outputs.shards) }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # Bare metal uses Ubuntu 24.04, which does not have `make` and `build-essential`.
      - name: Install make and build-essential
        run: sudo apt-get update && sudo apt-get install -y make build-essential
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
          check-latest: true
          cache-dependency-path: "**/go.sum"
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@63f3e98b61959fe67f146a3ff022e4136fe9bb9c # v4.17.6
        with:
          mode: walltime
          allow-empty: true
          # CodSpeed runs extremely slow when there are 128 processes involved, which is the number
          # of CPUs on the bare metal machine. Limiting the number of processes to 4 helps mitigate this. 4 also matches the number of CPUs on GitHub runners.
          #
          # CodSpeed overrides the default benchtime if we don't explicitly specify it.
          # Having this would avoid running benchmark for more than 1 hour.
          #
          # The benchtime is adjusted to 500 ms to speed up the benchmark time.
          # Per https://github.com/open-telemetry/community/issues/2331#issuecomment-2356403352
          run: GOMAXPROCS=4 make benchmark/${{matrix.shard}} ARGS=-benchtime=500ms
