# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: build
on:
  push:
    branches:
      - main
  pull_request:
env:
  DEFAULT_GO_VERSION: "~1.26.0"
# Declare default permissions as read only.
permissions: read-all
jobs:
  compatibility-cross-build:
    strategy:
      matrix:
        go-version: ["1.26.0", "1.25.0"]
        include:
          - goos: aix
            goarch: ppc64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: js
            goarch: wasm
          - goos: linux
            goarch: "386"
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: ppc64le
          - goos: linux
            goarch: riscv64
          - goos: linux
            goarch: arm
            goarm: "7"
          - goos: linux
            goarch: s390x
          - goos: windows
            goarch: "386"
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache-dependency-path: "**/go.sum"
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: make build

  test-cross-build:
    runs-on: ubuntu-latest
    needs: [compatibility-cross-build]
    if: always()
    steps:
      - name: Test if compatibility-cross-build passed
        run: |
          echo ${{ needs.compatibility-cross-build.result }}
          test ${{ needs.compatibility-cross-build.result }} == "success"
