name: codespell
on:
  push:
    branches:
      - main
  pull_request:
# Declare default permissions as read only.
permissions: read-all
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Codespell
        run: make codespell
      - run: make check-clean-work-tree
