name: Markdown

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
  # Everyday at 9:00 AM.
  - cron: "0 9 * * *"

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint-markdown:
    permissions:
      issues: write # required for creating issues from markdown lint reports
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Run linter
      id: markdownlint
      uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
      with:
        config: .markdownlint-cli2.yaml
        fix: false
        globs: |
          '**/*.md'
      continue-on-error: true

    - name: Manage issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        number=$(gh issue list --search "in:title Workflow failed: $GITHUB_WORKFLOW" --limit 1 --json number -q .[].number)

        echo $number

        if [[ $number ]]; then
          if [[ "${{ steps.markdownlint.outcome }}" != "failure" ]]; then
            gh issue close $number
          fi
        elif [[ "${{ steps.markdownlint.outcome }}" == "failure"  ]]; then
          gh issue create --title "Workflow failed: $GITHUB_WORKFLOW (#$GITHUB_RUN_NUMBER)" \
                          --body "See [$GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)." \
                          --label "report,bot-generated"
        fi
