name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '21 1 * * 5' # weekly at 01:21 UTC on Friday
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read # for actions/checkout
      security-events: write # for zizmor to upload SARIF results
    uses: open-telemetry/shared-workflows/.github/workflows/zizmor.yml@8079110d7e793bd38b1a5219ef8f8280dab9139e # v0.7.0
