name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '21 1 * * 5' # weekly at 01:21 UTC on Friday
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read # for actions/checkout
      security-events: write # for zizmor to upload SARIF results
    uses: open-telemetry/shared-workflows/.github/workflows/zizmor.yml@62d5939b47144252763c5ff9fffe8c20d76cd806 # v0.4.0
