name: Zizmor

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '21 1 * * 5' # weekly at 01:21 UTC on Friday
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read # for actions/checkout
      security-events: write # for zizmor to upload SARIF results
    uses: open-telemetry/shared-workflows/.github/workflows/zizmor.yml@03559ef555db0eae5d85c3c6347d1530243e7aa7 # v0.13.0
